package com.wilsonlimsetiawan.iaproject;
import java.awt.CardLayout;
import java.math.BigDecimal;
import java.math.MathContext;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class GUI extends javax.swing.JFrame {
    DefaultTableModel model;
    
    public GUI() {
        initComponents();
        model = (DefaultTableModel) peakTimeTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ParentPanel = new javax.swing.JPanel();
        MainMenu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PeakTimePanel = new javax.swing.JPanel();
        mainMenuButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        peakTimeTable = new javax.swing.JTable();
        changePeakStatusButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ForecastPanel = new javax.swing.JPanel();
        mainMenuButton1 = new javax.swing.JButton();
        addressOne = new javax.swing.JTextField();
        addressTwo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        forecastPriceButton = new javax.swing.JButton();
        currentTimeBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        timeOfJourneyBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        endResultPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        finalPriceField = new javax.swing.JTextField();
        mainMenuButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        finalRainField = new javax.swing.JTextField();
        finalDistanceField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        ratePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        priceTable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        mainMenuButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ParentPanel.setLayout(new java.awt.CardLayout());

        jButton1.setText("Forecast");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        settingsButton.setText("Settings");
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        jLabel2.setText(" Main Menu");

        javax.swing.GroupLayout MainMenuLayout = new javax.swing.GroupLayout(MainMenu);
        MainMenu.setLayout(MainMenuLayout);
        MainMenuLayout.setHorizontalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(202, 202, 202))
        );
        MainMenuLayout.setVerticalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
        );

        ParentPanel.add(MainMenu, "HomeScreenCard");

        mainMenuButton.setText("Main Menu");
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        peakTimeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Time", "Peak?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(peakTimeTable);

        changePeakStatusButton.setText("Change Peak Status");
        changePeakStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePeakStatusButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Settings");

        javax.swing.GroupLayout PeakTimePanelLayout = new javax.swing.GroupLayout(PeakTimePanel);
        PeakTimePanel.setLayout(PeakTimePanelLayout);
        PeakTimePanelLayout.setHorizontalGroup(
            PeakTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeakTimePanelLayout.createSequentialGroup()
                .addGroup(PeakTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PeakTimePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(changePeakStatusButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PeakTimePanelLayout.createSequentialGroup()
                        .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1)
                        .addGap(0, 203, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PeakTimePanelLayout.setVerticalGroup(
            PeakTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeakTimePanelLayout.createSequentialGroup()
                .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(changePeakStatusButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PeakTimePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ParentPanel.add(PeakTimePanel, "PeakTimeCard");

        mainMenuButton1.setText("Main Menu");
        mainMenuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButton1ActionPerformed(evt);
            }
        });

        addressOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressOneActionPerformed(evt);
            }
        });

        addressTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTwoActionPerformed(evt);
            }
        });

        jLabel3.setText("Starting Point:");

        jLabel4.setText("Destination:");

        jLabel5.setText("Time of Journey:");

        forecastPriceButton.setText("Forecast Price!");
        forecastPriceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forecastPriceButtonActionPerformed(evt);
            }
        });

        currentTimeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentTimeBoxActionPerformed(evt);
            }
        });

        jLabel10.setText("Current Time:");

        timeOfJourneyBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeOfJourneyBoxActionPerformed(evt);
            }
        });

        jLabel11.setText(" Forecast");

        javax.swing.GroupLayout ForecastPanelLayout = new javax.swing.GroupLayout(ForecastPanel);
        ForecastPanel.setLayout(ForecastPanelLayout);
        ForecastPanelLayout.setHorizontalGroup(
            ForecastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ForecastPanelLayout.createSequentialGroup()
                .addGroup(ForecastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ForecastPanelLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(forecastPriceButton))
                    .addGroup(ForecastPanelLayout.createSequentialGroup()
                        .addComponent(mainMenuButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ForecastPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(ForecastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addGroup(ForecastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ForecastPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(ForecastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addressTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addressOne, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ForecastPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(ForecastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(timeOfJourneyBox, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(currentTimeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(79, 135, Short.MAX_VALUE))
        );
        ForecastPanelLayout.setVerticalGroup(
            ForecastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ForecastPanelLayout.createSequentialGroup()
                .addGroup(ForecastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ForecastPanelLayout.createSequentialGroup()
                        .addComponent(mainMenuButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ForecastPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(ForecastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(currentTimeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ForecastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(timeOfJourneyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(ForecastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addressOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ForecastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addressTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(forecastPriceButton)
                .addGap(0, 38, Short.MAX_VALUE))
        );

        ParentPanel.add(ForecastPanel, "ForecastCard");

        jLabel6.setText("Final Price: ");

        finalPriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalPriceFieldActionPerformed(evt);
            }
        });

        mainMenuButton2.setText("Main Menu");
        mainMenuButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Distance (km) :");

        jLabel9.setText("Chance of rain:");

        finalRainField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalRainFieldActionPerformed(evt);
            }
        });

        finalDistanceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalDistanceFieldActionPerformed(evt);
            }
        });

        jButton2.setText("Review Prices ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout endResultPanelLayout = new javax.swing.GroupLayout(endResultPanel);
        endResultPanel.setLayout(endResultPanelLayout);
        endResultPanelLayout.setHorizontalGroup(
            endResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(endResultPanelLayout.createSequentialGroup()
                .addComponent(mainMenuButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(endResultPanelLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(endResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(endResultPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(finalDistanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(endResultPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(endResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(endResultPanelLayout.createSequentialGroup()
                                .addGroup(endResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(endResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(finalPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(finalRainField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(endResultPanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jButton2)))))
                .addContainerGap(202, Short.MAX_VALUE))
            .addGroup(endResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(endResultPanelLayout.createSequentialGroup()
                    .addGap(155, 155, 155)
                    .addComponent(jLabel7)
                    .addContainerGap(313, Short.MAX_VALUE)))
        );
        endResultPanelLayout.setVerticalGroup(
            endResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(endResultPanelLayout.createSequentialGroup()
                .addComponent(mainMenuButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(endResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(finalDistanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(endResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(finalRainField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(endResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(finalPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(endResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(endResultPanelLayout.createSequentialGroup()
                    .addGap(119, 119, 119)
                    .addComponent(jLabel7)
                    .addContainerGap(133, Short.MAX_VALUE)))
        );

        ParentPanel.add(endResultPanel, "endResultCard");

        priceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Prices"
            }
        ));
        priceTable.setToolTipText("");
        jScrollPane2.setViewportView(priceTable);

        jButton3.setText("Higher");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        mainMenuButton3.setText("Main Menu");
        mainMenuButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Lower");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel12.setText("Predicted vs Real Prices?");

        javax.swing.GroupLayout ratePanelLayout = new javax.swing.GroupLayout(ratePanel);
        ratePanel.setLayout(ratePanelLayout);
        ratePanelLayout.setHorizontalGroup(
            ratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratePanelLayout.createSequentialGroup()
                .addGroup(ratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ratePanelLayout.createSequentialGroup()
                        .addComponent(mainMenuButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel12))
                    .addGroup(ratePanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addGroup(ratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3)
                            .addComponent(jButton4))))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        ratePanelLayout.setVerticalGroup(
            ratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ratePanelLayout.createSequentialGroup()
                .addGroup(ratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainMenuButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ratePanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(ratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ratePanelLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );

        ParentPanel.add(ratePanel, "rateCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ParentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ParentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
//Method to populate the peakTimeTable
 public void populateTable(){
    for (int i = 0;i<Peak.peakTime.length; i++)
    {
        peakTimeTable.setValueAt(Peak.peakTime[i], i, 1);
        peakTimeTable.setValueAt(Peak.time[i], i, 0);
    }   
  }
 
 public void fillPriceTable(){
     for (int i = 0; i<arrayOfPrices.size(); i++)
     {
         priceTable.setValueAt(arrayOfPrices.get(i), i, 0);
     }
 }

ArrayList<Double> arrayOfPrices = new ArrayList<Double>();
double generalMultiplier = 1.5;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      CardLayout card =(CardLayout) ParentPanel.getLayout();
      card.show(ParentPanel, "ForecastCard");
      for (int i = 0;i<Peak.peakTime.length; i++)
        {
            currentTimeBox.addItem(Peak.time[i]);
            timeOfJourneyBox.addItem(Peak.time[i]);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    //Button to bring you from main menu to settings, populates the peakTimeTable using the method
    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
      CardLayout card =(CardLayout) ParentPanel.getLayout();
      card.show(ParentPanel, "PeakTimeCard");
      populateTable();     
    }//GEN-LAST:event_settingsButtonActionPerformed

    //Button to bring you back to mainmenu from settings
    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
      CardLayout card =(CardLayout) ParentPanel.getLayout();
      card.show(ParentPanel, "HomeScreenCard");
    }//GEN-LAST:event_mainMenuButtonActionPerformed
    
    //Button which changes a particular times Peak status and autoamtically repopulates the table.
    private void changePeakStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePeakStatusButtonActionPerformed
        int selectedTime = peakTimeTable.getSelectedRow();
        boolean currentValue = Peak.checkPeakTime(selectedTime);
        //!currentvalue ensures a switch between true/false
        Peak.editPeakTime(selectedTime, !currentValue);
        CardLayout card =(CardLayout) ParentPanel.getLayout();
        card.show(ParentPanel, "PeakTimeCard");
        populateTable();
    }//GEN-LAST:event_changePeakStatusButtonActionPerformed

    private void mainMenuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButton1ActionPerformed
      CardLayout card =(CardLayout) ParentPanel.getLayout();
      card.show(ParentPanel, "HomeScreenCard");
      currentTimeBox.removeAllItems();
      timeOfJourneyBox.removeAllItems();
      
    }//GEN-LAST:event_mainMenuButton1ActionPerformed

    private void forecastPriceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forecastPriceButtonActionPerformed
        //Firstly, manipulation of PeakTime Data
        Peak.calculatePeakTimeMultiplier();
        
        //Secondly, Manipulation of the distance
        try
        {
            Distance.initGoogleMapAPI(Distance.API_KEY,
            addressOne.getText()+",SG",addressTwo.getText()+",SG");   
        }
        catch(Exception ex)
        {
         JOptionPane.showMessageDialog(ParentPanel, "There was an error with the locations");
        }
        
        //Thirdly, Manipulation of the weather
        try
        {
            Weather.initWeatherAPI();
        }
        catch(Exception ex)
        {
         JOptionPane.showMessageDialog(ParentPanel,"There was an error with the weather!");
        }
        //final calculations to come to a prediction in price
        double calculatedPrice =  generalMultiplier *Peak.peakTimeMultiplier * 
        Distance.realDistanceApart * Weather.weatherMultiplier;
        
        BigDecimal bd = new BigDecimal(calculatedPrice);
        bd = bd.round(new MathContext(3));
        double finalPrice = bd.doubleValue();
        
        
        String finalValue = Double.toString(finalPrice);
        
        //showcase the final price on another panel
        CardLayout card =(CardLayout) ParentPanel.getLayout();
         card.show(ParentPanel, "endResultCard");
         finalPriceField.setText(finalValue);
         finalRainField.setText(Weather.justTheChance);
         finalDistanceField.setText(Distance.finalDistance);
         arrayOfPrices.add(finalPrice);
         
         
    }//GEN-LAST:event_forecastPriceButtonActionPerformed

    private void currentTimeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentTimeBoxActionPerformed
        
    }//GEN-LAST:event_currentTimeBoxActionPerformed

    private void addressOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressOneActionPerformed

    private void addressTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTwoActionPerformed

    private void finalPriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalPriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finalPriceFieldActionPerformed

    private void mainMenuButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButton2ActionPerformed
      CardLayout card =(CardLayout) ParentPanel.getLayout();
      card.show(ParentPanel, "HomeScreenCard");
      currentTimeBox.removeAllItems();
      timeOfJourneyBox.removeAllItems();
      addressOne.setText("");
      addressTwo.setText("");
      finalPriceField.setText("");
      finalRainField.setText("");
      finalDistanceField.setText("");
    }//GEN-LAST:event_mainMenuButton2ActionPerformed

    private void finalRainFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalRainFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finalRainFieldActionPerformed

    private void finalDistanceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalDistanceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finalDistanceFieldActionPerformed

    private void timeOfJourneyBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeOfJourneyBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeOfJourneyBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      CardLayout card =(CardLayout) ParentPanel.getLayout();
      card.show(ParentPanel, "rateCard");
      fillPriceTable();
      currentTimeBox.removeAllItems();
      timeOfJourneyBox.removeAllItems();
      addressOne.setText("");
      addressTwo.setText("");
      finalPriceField.setText("");
      finalRainField.setText("");
      finalDistanceField.setText("");       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mainMenuButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButton3ActionPerformed
      CardLayout card =(CardLayout) ParentPanel.getLayout();
      card.show(ParentPanel, "HomeScreenCard");
      currentTimeBox.removeAllItems();
      timeOfJourneyBox.removeAllItems();
      addressOne.setText("");
      addressTwo.setText("");
      finalPriceField.setText("");
      finalRainField.setText("");
      finalDistanceField.setText("");
    }//GEN-LAST:event_mainMenuButton3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      generalMultiplier = generalMultiplier - 0.1;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      generalMultiplier = generalMultiplier + 0.1;
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });   
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ForecastPanel;
    private javax.swing.JPanel MainMenu;
    private javax.swing.JPanel ParentPanel;
    private javax.swing.JPanel PeakTimePanel;
    private javax.swing.JTextField addressOne;
    private javax.swing.JTextField addressTwo;
    private javax.swing.JButton changePeakStatusButton;
    public static javax.swing.JComboBox<String> currentTimeBox;
    private javax.swing.JPanel endResultPanel;
    public static javax.swing.JTextField finalDistanceField;
    public static javax.swing.JTextField finalPriceField;
    public static javax.swing.JTextField finalRainField;
    private javax.swing.JButton forecastPriceButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JButton mainMenuButton1;
    private javax.swing.JButton mainMenuButton2;
    private javax.swing.JButton mainMenuButton3;
    public static javax.swing.JTable peakTimeTable;
    private javax.swing.JTable priceTable;
    private javax.swing.JPanel ratePanel;
    private javax.swing.JButton settingsButton;
    public static javax.swing.JComboBox<String> timeOfJourneyBox;
    // End of variables declaration//GEN-END:variables
}
